/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package io.eldermael.jvmmx.localstack.demo;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import com.amazonaws.services.lambda.runtime.events.APIGatewayV2HTTPResponse;
import com.amazonaws.services.lambda.runtime.events.SNSEvent;
import lombok.extern.slf4j.Slf4j;
import software.amazon.awssdk.services.sqs.SqsClient;
import software.amazon.awssdk.services.sqs.model.SendMessageRequest;
import software.amazon.awssdk.services.sqs.model.SendMessageResponse;

@Slf4j
public class Handler implements RequestHandler<SNSEvent, APIGatewayV2HTTPResponse> {

  private final String queueUrl;
  private final SqsClient sqsClient;

  public Handler() {
    this.queueUrl = System.getenv("QUEUE_URL");
    this.sqsClient = SqsClient.builder().build();
  }

  public Handler(String queueUrl, SqsClient sqsClient) {
    this.queueUrl = queueUrl;
    this.sqsClient = sqsClient;
  }

  @Override
  public APIGatewayV2HTTPResponse handleRequest(SNSEvent input, Context context) {
    log.info("Running lambda request: {}", input);
    log.info("Function name: {}", context.getFunctionName());
    SendMessageResponse response = this.sqsClient.sendMessage(SendMessageRequest.builder()
        .queueUrl(this.queueUrl)
        .messageBody("test")
        .build());

    return APIGatewayV2HTTPResponse.builder()
        .withStatusCode(200)
        .build();
  }
}
